<?php 
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    RCCsv_Cron
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<style>
* {
  box-sizing: border-box;
}

input[type=text], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 4px;
  resize: vertical;
}

label {
  padding: 12px 12px 12px 0;
  display: inline-block;
}

input[type=submit] {
  background-color: #04AA6D;
  color: white;
  padding: 12px 20px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  float: right;
}

input[type=submit]:hover {
  background-color: #45a049;
}

.container {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
}
.col-15 {
  float: left;
  width: 15%;
  margin-top: 6px;
}
.col-20 {
  float: left;
  width: 20%;
  margin-top: 6px;
}
.col-25 {
  float: left;
  width: 25%;
  margin-top: 6px;
}

.col-75 {
  float: left;
  width: 75%;
  margin-top: 6px;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Responsive layout - when the screen is less than 600px wide, make the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 600px) {
  .col-25, .col-75, input[type=submit] {
    width: 100%;
    margin-top: 0;
  }
}
</style>
</head>
<body>
<?php
$PostValue = $this->getRequest()->getPost();
print_r($PostValue);
  $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); // Instance of object manager
  $resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
  $connection = $resource->getConnection();
  $tableName = $resource->getTableName('rccsv_settings'); //gives table name with prefix
  $sql = "Select * FROM " . $tableName;
  $result = $connection->fetchAll($sql);
if($PostValue['form_key']!='')
{
  
  print_r($result);
  if(empty($result))
  {
    $sql = "Insert Into " . $tableName . " (cron_file_path, minutes) Values ('".$PostValue['cron_file_path']."','".$PostValue['cron_schedule']."')";
    $connection->query($sql);

  }
  else
  {
      $sql = "Update " . $tableName . " Set cron_file_path = '".$PostValue['cron_file_path']."', minutes = '".$PostValue['minutes']."' , hours = '".$PostValue['hours']."', day_of_month = '".$PostValue['day_of_month']."', month = '".$PostValue['month']."', week = '".$PostValue['week']."' where id = 1";
      $connection->query($sql);
  }
  
}
?>
<h2>Cron Settings</h2>

<div class="container">
  <form action="<?php echo $this->getUrl('rccsv/create/index', ['_secure' => true]);?>" method="post">
    <div class="row">
      <div class="col-25">
        <label for="fname"><b>File Path</b></label>
      </div>
      <div class="col-75">
        <input type="text" id="cron_file_path" name="cron_file_path" placeholder="cron_file_path" value="<?php echo $result[0]['cron_file_path'];?>">
      </div>
    </div>
   
    <div class="row">
      <div class="col-15">
          <b>Minutes</b>
          <br>
          <input type="number" name="minutes" value="<?php echo $result[0]['minutes'];?>" min="0" max="60">
      </div>
      <div class="col-15">
          <b>Hour</b>
          <br>
          <input type="number" name="hours" value="<?php echo $result[0]['hours'];?>" min="0" max="24">
      </div>
      <div class="col-15">
          <b>Day of Month</b>
          <br>
          <input type="number" name="day_of_month" value="<?php echo $result[0]['day_of_month'];?>" min="0" max="31">
      </div>
      <div class="col-20">
          <b>Month</b>
          <br>
          <select name="month">
            <option value="january" <?php if($result[0]['month']=="january"){ ?> selected <?php }else{ ?>selected=" " <?php } ?>>January</option>
            <option value="february"<?php if($result[0]['month']=="february"){ ?> selected <?php }else{ ?>selected=" " <?php } ?>>February</option>
            <option value="march" <?php if($result[0]['month']=="march"){ ?> selected <?php }else{ ?>selected=" " <?php } ?>>March</option>
            <option value="april" <?php if($result[0]['month']=="april"){ ?> selected <?php }else{ ?>selected=" " <?php } ?>>April</option>
            <option value="may" <?php if($result[0]['month']=="may"){ ?> selected <?php }else{ ?>selected=" " <?php } ?>>May</option>
            <option value="june" <?php if($result[0]['month']=="june"){ ?> selected <?php }else{ ?>selected=" " <?php } ?>>June</option>
            <option value="july" <?php if($result[0]['month']=="july"){ ?> selected <?php }else{ ?>selected=" " <?php } ?>>July</option>
            <option value="august" <?php if($result[0]['month']=="august"){ ?> selected <?php }else{ ?>selected=" " <?php } ?>>>August</option>
            <option value="september" <?php if($result[0]['month']=="september"){ ?> selected <?php }else{ ?>selected=" " <?php } ?>>September</option>
            <option value="october" <?php if($result[0]['month']=="october"){ ?> selected <?php }else{ ?>selected=" " <?php } ?>>October</option>
            <option value="november"<?php if($result[0]['month']=="november"){ ?> selected <?php }else{ ?>selected=" " <?php } ?>>November</option>
            <option value="december" <?php if($result[0]['month']=="december"){ ?> selected <?php }else{ ?>selected=" " <?php } ?>>December</option>
          </select>
      </div>
      <div class="col-20">
          <b>Week Day</b>
          <br>
          <select name="week">
            <option value="sunday"<?php if($result[0]['week']=="sunday"){ ?> selected="selected" <?php }else{ ?>selected=" " <?php } ?>>Sunday</option>
            <option value="monday"<?php if($result[0]['week']=="monday"){ ?> selected="selected" <?php }else{ ?>selected=" " <?php } ?>>Monday</option>
            <option value="tuesday"<?php if($result[0]['week']=="tuesday"){ ?> selected="selected" <?php }else{ ?>selected=" " <?php } ?>>Tuesday</option>
            <option value="wednesday"<?php if($result[0]['week']=="wednesday"){ ?> selected="selected" <?php }else{ ?>selected=" " <?php } ?>>Wednesday</option>
            <option value="thursday"<?php if($result[0]['week']=="thursday"){ ?> selected="selected" <?php }else{ ?>selected=" " <?php } ?>>Thursday</option>
            <option value="friday"<?php if($result[0]['week']=="friday"){ ?> selected="selected" <?php }else{ ?>selected=" " <?php } ?>>Friday</option>
            <option value="saturday"<?php if($result[0]['week']=="saturday"){ ?> selected="selected" <?php }else{ ?>selected=" " <?php } ?>>Saturday</option>
          </select>
      </div>
    </div>
    <div class="row">
      <div class="col-25">
        <label for="lname"><b>Image Path</b></label>
      </div>
      <div class="col-75">
        <input type="text" id="img_path" name="img_path" placeholder="img_path" value="pub/media/catalog/product/" readonly>
      </div>
    </div>
    <div class="row" style="text-align: center;">
      <input type="submit" value="Submit">
    </div>
    <input name="form_key" type="hidden" value="<?php /* @escapeNotVerified */ echo $block->getFormKey(); ?>" />
  </form>
</div>

